//
// Created by User on 5/15/2023.
//

#ifndef UNIVERSITY_PROGRAM_SYSTEM_SIMULATION_TEST1_H
#define UNIVERSITY_PROGRAM_SYSTEM_SIMULATION_TEST1_H
#include <iostream>
void printSomething(int);
#endif //UNIVERSITY_PROGRAM_SYSTEM_SIMULATION_TEST1_H
